### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by yveskerwyn** [Artilium/GiG-ePortal#25]
I got the following error when logging in via http://197.227.35.157:81:

```
{"message":"Non valid JSON returned from server ","stacktrace":"Exception: Fatal error: "Undefined index: stateControl" in \/var\/www\/html\/Utils\/ErrorHandler.php:13\nStack trace:\n#0 \/var\/www\/html\/Security\/IdentityProviders\/ItsYouOnlineIdentityProvider.php(49): ArtaG8\\Utils\\ErrorHandler::GlobalErrorHandler(8, 'Undefined index...', '\/var\/www\/html\/S...', 49, Array)\n#1 \/var\/www\/html\/Security\/Handlers\/LoginHandler.php(51): ArtaG8\\Security\\IdentityProviders\\ItsYouOnlineIdentityProvider->Login('user:name,user:...', 'lci', 'http:\/\/eportalm...', 'cNUXt1g3cJXXAsa...', 'https:\/\/itsyou....', 'https:\/\/itsyou....', 'https:\/\/itsyou....')\n#2 [internal function]: ArtaG8\\Security\\Handlers\\LoginHandler->getIndex()\n#3 \/var\/www\/html\/vendor\/jdelrue\/phroute\/src\/Phroute\/Dispatcher.php(67): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/Security\/index.php(41): Phroute\\Phroute\\Dispatcher->dispatch('GET', '\/security\/login...')\n#5 {main}"}
```

**Comment by yveskerwyn** [comment]
OK this is only when using the above URL

It works as expected when using http://eportalma-staging.artilium.com:81
